# Generated by Django 4.1.2 on 2025-03-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confgrate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserR',
        ),
    ]
